project:
  type: website
  output-dir: docs

website:
  title: "Home Loan Advisor"
  sidebar:
    style: "docked"
    background: light
    contents:
      - href: index.qmd
        text: An Overview
      - href: proposal.qmd
        text: App Proposal
      - href: data.qmd
        text: The Data
      - href: models.qmd
        text: The Models
      - href: results.qmd
        text: Our Results
      - href: app.qmd
        text: The App
      - href: about.qmd
        text: About the Group

format:
  html:
    theme: litera
    title-block-banner: false
sidebar: true