project:
  type: website
  output-dir: docs

website:
  title: "Home Loan Advisor"
  sidebar:
    title: false
    logo: images/HLA-sqaure-logo.png
    style: "docked"
    background: light
    contents:
      - href: index.qmd
        text: An Overview
      - href: proposal.qmd
        text: App Proposal
      - href: data.qmd
        text: The Data
      - href: models.qmd
        text: The Models
      - href: results.qmd
        text: Our Results
      - href: mvp-presentation.qmd
        text: MVP Slideshow
      - href: https://aribamandavia12.shinyapps.io/Downloads/
        text: Presenntation App (Version 3)
      - href: https://homeloanadvisor.acmedia.uk/
        text: Final App (Version 2)
      - href: app.qmd
        text: App Version 1
      - href: about.qmd
        text: About the Group

format:
  html:
    theme: litera
    title-block-banner: false
sidebar: true